
using ApplicationCore.Execeptions;
using System;
using System.Threading.Tasks;

namespace DriveDrop.Api.Infrastructure.Idempotency
{
    public class RequestManager : IRequestManager
    {
        private readonly DriveDropContext _context;

        public RequestManager(DriveDropContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }


        public async Task<bool> ExistAsync(Guid id)
        {
            var request = await _context.
                FindAsync<ClientRequest>(id);

            return request != null;
        }

        public async Task CreateRequestForCommandAsync<T>(Guid id)
        { 
            var exists = await ExistAsync(id);

            var request = exists ? 
                throw new DriveDropException($"Request with {id} already exists") : 
                new ClientRequest()
                {
                    Id = id,
                    Name = typeof(T).Name,
                    Time = DateTime.UtcNow
                };

            _context.Add(request);

            await _context.SaveChangesAsync();
        }
    }
}
